---
# OTA (Over The Air) component
#
# Contains my common OTA setup.
#
# https://esphome.io/components/ota.html
#
substitutions:
  ota_password: !secret ota_password

ota:
  platform: esphome
  password: "${ota_password}"
  id: updates
