---
# ESPHome Core configuration
#
# Sets the defaults for the main core configuration of ESPHome devices.
#
# https://esphome.io/components/esphome.html
#

name: "esp-${system_name}"
comment: "${device_description}"
#build_path: "../.build/esph-${system_name}/"
