substitutions:
#  Pass these options on the command line with -s
#  system_name: light-bulb
#  friendly_name: Light Bulb
  device_description: "ESP8266 Tuya Light Bulb"

packages:
  board: !include ../boards/esp8266_no_usb.yaml
  light: !include ../components/lights/feit_bpa800_costco.yaml
