substitutions:
  #  Pass these options on the command line with -s
  system_name: konnected-1
  friendly_name: Konnected Panel 1
  device_description: "Konnected Alarm Panel"

esphome:
  <<: !include ../boards/.esphome.yaml
  name_add_mac_suffix: false

packages:
  <<: !include_dir_named ../components/common
  remote_package:
    url: https://github.com/konnected-io/konnected-esphome
    ref: master
    refresh: 1days
    files:
      - packages/alarm-panel-esp8266-base.yaml
      - packages/alarm-panel/zone1.yaml
      - packages/alarm-panel/zone2.yaml
      - packages/alarm-panel/zone3.yaml
      - packages/alarm-panel/zone4.yaml
      - packages/alarm-panel/zone5.yaml
      - packages/alarm-panel/zone6.yaml
      - packages/alarm-panel/alarm.yaml
      - packages/status-led.yaml

switch:
  - id: !extend siren
    pin:
      allow_other_uses: false

binary_sensor:
  - id: !extend zone1
    name: Smoke Detector
    device_class: smoke

  - id: !extend zone2
    name: Master Window
    device_class: window

  - id: !extend zone3
    name: Bedroom Window
    device_class: window

  - id: !extend zone4
    name: Family Room Window
    device_class: window

  - id: !extend zone5
    name: Loft Window
    device_class: window

  - id: !extend zone6
    name: Interior Garage Door
    device_class: door
