
substitutions:
  system_name: storage-sensor
  friendly_name: Storage Sensor
  device_description: "ESP32 monitoring storage unit door"
  wake_pin: GPIO4
  status_pin: GPIO2
  address: 10.0.50.10

packages:
  board: !include ../boards/esp32doit.yaml
  wireguard: !include ../components/core/wireguard.yaml
  web: !include ../components/core/web_server.yaml
  http: !include ../components/core/http_request.yaml
  ota_http: !include ../components/core/ota_http.yaml

wifi:
  use_address: $address

ota:
  on_begin:
    then:
#      - deep_sleep.prevent: sleeper
      - http_request.post:
          url: https://ntfy.zuba.dev/esp-updates
          verify_ssl: false
          headers:
            Authorization: !secret ntfy_token
          body: "OTA update is starting for storage-sensor"
  on_end:
    then:
      - http_request.post:
          url: https://ntfy.zuba.dev/esp-updates
          verify_ssl: false
          headers:
            Authorization: !secret ntfy_token
          body: "OTA update is complete for storage-sensor"
      - http_request.get:
          url: https://esp.zuba.dev/complete/storage-sensor.bin
          verify_ssl: false
  on_error:
    then:
#      - deep_sleep.allow: sleeper
      - http_request.post:
          url: https://ntfy.zuba.dev/esp-updates
          verify_ssl: false
          headers:
            Authorization: !secret ntfy_token
          body: "Update had an error for storage-sensor"

#deep_sleep:
#  id: sleeper
#  run_duration: 30s
#  sleep_duration: 2min
#  wakeup_pin:
#    number: $wake_pin
#    allow_other_uses: true
#  wakeup_pin_mode: INVERT_WAKEUP

logger:
  level: INFO

binary_sensor:
  - platform: gpio
    pin:
      number: $wake_pin
      mode: INPUT_PULLDOWN
      inverted: true
#      allow_other_uses: true
    name: "Door Sensor"
    device_class: garage_door

light:
  - platform: status_led
    id: status_indicator
    pin: $status_pin

interval:
  - interval: 10s
    then:
      if:
        condition:
          binary_sensor.is_on: wg_status
        then:
          - http_request.send:
              method: HEAD
              url: https://esp.zuba.dev/firmware/storage-sensor.bin
              verify_ssl: false
              on_response:
                then:
                  - logger.log:
                      format: "Response status: %d"
                      args:
                        - status_code

#          - ota_http.flash:
#              url: https://esp.zuba.dev/firmware/storage-sensor.bin
#              verify_ssl: false
  - interval: 1s
    then:
      if:
        condition:
          binary_sensor.is_on: wg_status
        then:
          - light.turn_on: status_indicator
          - delay: 500ms
          - light.turn_off: status_indicator
        else:
          - light.turn_off: status_indicator

wireguard:
  address: $address
  netmask: 0.0.0.0
  peer_public_key: UtURYaA+v7dN/vXWddlaviSimvskQw+kZeCYhfyIsBY=
  peer_endpoint: vpn.zuba.dev
  private_key: !secret wg_storage_key
